CREATE TABLE ACCOUNT (
	ID 				numeric(19, 0) 		NOT NULL,
	USERNAME 		varchar(30) 		NOT NULL UNIQUE,
	PASSWORD 		varchar(80) 		NOT NULL,
	'ACCESS' 		numeric(19, 0) 		NOT NULL, 
	
	PRIMARY KEY (ID)
);
	
CREATE TABLE ITEM_PER_ORDER (
	ID 				numeric(19, 0) 		NOT NULL, 
	ORDER_ID 		numeric(19, 0) 		NOT NULL, 
	ITEM_ID 		numeric(19, 0) 		NOT NULL, 
	AMOUNT 			numeric(19, 0) 		NOT NULL, 
	PHOTO_ID 		numeric(19, 0) 		NOT NULL, 
	
	PRIMARY KEY (ID)
);
	
CREATE TABLE ITEM (
	ID 				numeric(19, 0) 		NOT NULL, 
	DESCRIPTION 	varchar(255) 		NOT NULL, 
	PRICE_PER_ITEM 	numeric(19, 2) 		NOT NULL, 
	ACTIVE 			numeric(1, 0) 		NOT NULL, 
	
	PRIMARY KEY (ID)
);
	
CREATE TABLE 'ORDER' (
	ID 				numeric(19, 0) 		NOT NULL, 
	CUSTOMER_ID 	numeric(19, 0) 		NOT NULL,
	ORDERDATE 		datetime 			NOT NULL, 

	PRIMARY KEY (ID)
);

CREATE TABLE CUSTOMER (
	ID 				numeric(19, 0) 		NOT NULL, 
	NAME 			varchar(100) 		NOT NULL, 
	ADRES 			varchar(200) 		NOT NULL, 
	ZIPCODE 		varchar(10)			NOT NULL, 
	CITY 			varchar(100)		NOT NULL, 
	EMAIL 			varchar(200) 		NOT NULL UNIQUE,
	ACCOUNT_ID 		numeric(19, 0) 		NOT NULL UNIQUE,

	PRIMARY KEY (ID)
);
	
CREATE TABLE PHOTOGRAPHER (
	ID 				numeric(19, 0) 		NOT NULL,
	NAME 			varchar(200) 		NOT NULL, 
	ACCOUNT_ID 		numeric(19, 0) 		NOT NULL UNIQUE, 
	
	PRIMARY KEY (ID)
);
	
CREATE TABLE PHOTO (
	ID 				numeric(19, 0) 		NOT NULL, 
	CODE 			varchar(100) 		NOT NULL UNIQUE, 
	PHOTOGRAPHER_ID numeric(19, 0) 		NOT NULL, 
	PRICE 			numeric(19, 2) 		NOT NULL, 
	DATA_BIG 		blob 				NOT NULL,
	DATA_SMALL 		blob,
	
	PRIMARY KEY (ID)
);
	
ALTER TABLE ITEM_PER_ORDER 
	ADD INDEX FKITEM_PER_O566254 (ITEM_ID), 
	ADD CONSTRAINT FKITEM_PER_O566254 
		FOREIGN KEY (ITEM_ID) 
		REFERENCES ITEM (ID)
;
	
ALTER TABLE PHOTOGRAPHER 
	ADD INDEX FKPHOTOGRAPH33628 (ACCOUNT_ID), 
	ADD CONSTRAINT FKPHOTOGRAPH33628 
		FOREIGN KEY (ACCOUNT_ID) 
		REFERENCES ACCOUNT (ID)
;
	
ALTER TABLE PHOTO 
	ADD INDEX FKPHOTO967187 (PHOTOGRAPHER_ID), 
	ADD CONSTRAINT FKPHOTO967187 
		FOREIGN KEY (PHOTOGRAPHER_ID) 
		REFERENCES PHOTOGRAPHER (ID)
;
		
ALTER TABLE ITEM_PER_ORDER 
	ADD INDEX FKITEM_PER_O418628 (PHOTO_ID), 
	ADD CONSTRAINT FKITEM_PER_O418628 
		FOREIGN KEY (PHOTO_ID) 
		REFERENCES PHOTO (ID)
;
	
ALTER TABLE ITEM_PER_ORDER 
	ADD INDEX FKITEM_PER_O612022 (ORDER_ID), 
	ADD CONSTRAINT FKITEM_PER_O612022 
		FOREIGN KEY (ORDER_ID) 
		REFERENCES 'ORDER' (ID)
;
	
ALTER TABLE CUSTOMER 
	ADD INDEX FKCUSTOMER258870 (ACCOUNT_ID), 
	ADD CONSTRAINT FKCUSTOMER258870 
		FOREIGN KEY (ACCOUNT_ID) 
		REFERENCES ACCOUNT (ID)
;
	
ALTER TABLE 'ORDER'
	ADD INDEX FKORDER205112 (CUSTOMER_ID), 
	ADD CONSTRAINT FKORDER205112 
		FOREIGN KEY (CUSTOMER_ID) 
		REFERENCES CUSTOMER (ID)
;
	
	
INSERT INTO ACCOUNT
			(ID, 	USERNAME, 		PASSWORD, 	'ACCESS') 
	VALUES
			(0, 	'corpelijn',	'Welkom01',		1),
			(1,		'taskent'		'Welkom01', 	1),
			(2, 	'vijfeijke',	'Welkom01', 	1),
			(3,		'mierlo'		'Welkom01',		1),
			(4,		'horloo', 		'Welkom01',		1),
			(5, 	'dijk',			'Welkom01', 	1)
;






































